### ISSUE TITLE
HEX value without "#"

### ISSUE THREAD

**Issue by RkcCorian** [patrickbs96/ioBroker.twinkly#102]
**Is your feature request related to a problem? Please describe.**
- Nice adapter, many thanks! I have several lights, also with HEX-Value Data Points. There the value is without the "#" which saves a little bit screen space. Would it be possible change the DP value from e.g., "#ffffff" to simply "ffffff"?!

**Describe the solution you'd like**
- See description above

**Describe alternatives you've considered**
- No alternative. It is a yes or now I guess?!

**Additional context**
<img width="1740" alt="image" src="https://user-images.githubusercontent.com/79741077/146658438-f50666e1-0db5-4e04-b5f3-f6b9bdd8a939.png">

**Comment by patrickbs96** [comment]
Hi there, thanks.
I've updated the output of the DP in the new Version 0.2.7 to always display it as ffffff. Writing the value can be done by writing the hex value either as "#ffffff" or "ffffff" or even use the short hand "fff".

**Comment by RkcCorian** [comment]
Nice, many thanks!!!!!
