### ISSUE TITLE
Movie name not fully taken

### ISSUE THREAD

**Issue by RkcCorian** [patrickbs96/ioBroker.twinkly#103]
**Describe the bug**  
- Seems the movie name is cutted

**To Reproduce**  
- Create in the app a own effect (seems to be called movie here) with the name Nikolas Rot/Weiss

**Expected behavior**  
- Full name will be taken

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.
![image](https://user-images.githubusercontent.com/79741077/146672565-8ea5e564-7ed3-4668-a9e2-ffeab08f696a.png)

**Versions:**  
 - Adapter version: 0.2.7
 - JS-Controller version: Not sure, but latest official 🙈
 - Node version: 14.18.2
 - Operating system: Synology Docker

**Additional context**

**Comment by RkcCorian** [comment]
Additional question... how can I controll? Via number only or also via name (assuming it will take the full name 😀)?

**Comment by patrickbs96** [comment]
> Additional question... how can I controll? Via number only or also via name (assuming it will take the full name 😀)?

You can only control them by the number.

Would you like a state where you could control all modes with? E.g.
"movie:Nikolas Rot/Weiss", "movie:0", "effect:2", "playlist:2", "color:ffffff"

**Comment by RkcCorian** [comment]
> > Additional question... how can I controll? Via number only or also via name (assuming it will take the full name 😀)?
> 
> You can only control them by the number.
OK

> 
> Would you like a state where you could control all modes with? E.g. "movie:Nikolas Rot/Weiss", "movie:0", "effect:2", "playlist:2", "color:ffffff"
No, I think this is not needed 😀

**Comment by patrickbs96** [comment]
I think ioBroker might complain about this by showing warnings if you would write a String to a Number field anyway... 

Okay, so I checked what the problem is with the name and it seems that the Twinkly App is cutting off the end when saving it to the lights. And as I am just reading the info what is on the lights I'm not getting the full name...
Unfortunately nothing I can control... 
15 characters seems to be the max length

**Comment by RkcCorian** [comment]
Ok, then I will take this input for my naming :-) On the other side... as I have to indentify via number it is "only" the visible name that I can adopt in my VIS anyway... then you can close without change but many thanks for the info!!!!

**Comment by patrickbs96** [comment]
Isn't there an option to use a combobox? Then you could use your own names and the values to be set are just the numbers.
This might be extremely helpful if you've uploaded multiple movies and you want to change the active movie 😄

**Comment by RkcCorian** [comment]
There is 😀
