### ISSUE TITLE
Harmonize mode naming

### ISSUE THREAD

**Issue by RkcCorian** [patrickbs96/ioBroker.twinkly#104]
**Is your feature request related to a problem? Please describe.**
- Inconsistent naming: movie: on. I mean also "effect" would be something "on" 😀
![image](https://user-images.githubusercontent.com/79741077/146672723-b117bc0c-e126-49ef-ac16-f6cfcc20a325.png)

**Describe the solution you'd like**
- Change to movie:movie or something comparable. To be honest I do not understand the real difference between effect and movie but I guess this is given by Twinkly?!

**Describe alternatives you've considered**

**Additional context**

**Comment by patrickbs96** [comment]
Yeah I'll update that later never really put any energy into giving those Mode states good names. 😆 I see want you mean here though...
The difference between Movie and Effect is, that you select the Movies yourself and the Effects are included by factory default and can't be changed.

**Comment by RkcCorian** [comment]
😂 Just have trouble to find a good german translation for my wife 🙈😂

**Comment by patrickbs96** [comment]
Maybe Szene? 😅

**Comment by patrickbs96** [comment]
New version is being built at the moment and should be available through npm in roughly 5 minutes 😄

**Comment by RkcCorian** [comment]
Works 😀 Many many thanks!!!
