### ISSUE TITLE
Movie identification not psossible as only "0" is always available

### ISSUE THREAD

**Issue by RkcCorian** [patrickbs96/ioBroker.twinkly#105]
**Describe the bug**  
- I have in the meantime several "movies". When I select different movies in the adapter it is always visible as "0". The string is changing but I understood from the past the the number shall identifiy the dedicated movie. This is not possible as there is only "0" and the string will change always dependant on the actual selected (via Twinkly app) movie

**To Reproduce**  
- Change movie in Twinkly app an check DP ```ledMovie```

**Expected behavior**  
- See above :-)

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 0.2.8
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by patrickbs96** [comment]
The thing is by activating a movie on the lights only that movie is available. But there is a workaround 😉 
You need to upload the movies as a playlist and then change the ledMode to Movie. You can then switch between the uploaded movies 😄

**Comment by RkcCorian** [comment]
Ahhh, ok... it works. The advantage is that I can define the number myself and it will not change accidently. But it is a hard "trick"

**Comment by patrickbs96** [comment]
It's unfortunately nothing I've got the control over so this is the only way...

I actually did document this behaviour in the section with all the available states. I might extend it though 😆
