### ISSUE TITLE
Choose last mode before switching off

### ISSUE THREAD

**Issue by RkcCorian** [patrickbs96/ioBroker.twinkly#112]
**Is your feature request related to a problem? Please describe.**

It is nice that in the meantime it is possible to choose the mode which shall be active once the status goes on again. What I did in my personal script... I reactive the mode that was active before switching off.

**Describe the solution you'd like**

Would be nice if such an option would be available (as additional entry in the dropdown?!)

**Describe alternatives you've considered**

**Additional context**

**Comment by patrickbs96** [comment]
The only problem that could occur is that if the adapter has been of for a while the last "On" State could be different.

But apart from it sounds like a great idea 😊

**Comment by RkcCorian** [comment]
> The only problem that could occur is that if the adapter has been off for a while the last "On" State could be different.
> 
> But apart from that it sounds like a great idea 😊

Looking forward for the implementation. The only problem is that my Twinkly will be removed at sunday as christmas is over 🙈

**Comment by patrickbs96** [comment]
finally had some time to look at it 🙈 

Few more months until Christmas and then you can use it 😄

**Comment by RkcCorian** [comment]
Nice! I hope I remember at Christmas 🙈😁
