### ISSUE TITLE
Bightness no longer readable / writable

### ISSUE THREAD

**Issue by RkcCorian** [patrickbs96/ioBroker.twinkly#182]
**Describe the bug**  

**To Reproduce**  
Look at twinkly.0.<WhatEverName>.ledBri

**Expected behavior**  
I can see / control the brightness

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 1.0.3

**Additional context**  
There were several firmware updates. I guess the API has changed.

Many thanks in advance!!!

**Comment by RkcCorian** [comment]
@patrickbs96 : Alle Jahre sieht man sich hier wieder, meistens gen Weihnachten :-)

**Comment by patrickbs96** [comment]
Hi, sorry ich hatte den Bug letzten Monat bereits behoben gehabt aber vergessen ein neues Release zu erzeugen 🤣 
Bitte upgrade auf die Version `1.0.6` damit sollte es wieder funktionieren :-)

**Comment by RkcCorian** [comment]
Moin! Ja, funktioniert :-) Wann kommt es im Stable?
Viele Grüße!

**Comment by patrickbs96** [comment]
Ich habe gerade noch einen Bug bezüglich der Auswahl von Playlist-Einträgen korrigiert.
Wenn das gleich alles auf npm übertragen ist übertrage ich es dann direkt ins stable :-)
