### ISSUE TITLE
Error: proxyFromEnv.getProxyForUrl is not a function

### ISSUE THREAD

**Issue by basti85goe** [patrickbs96/ioBroker.twinkly#192]
**Describe the bug**  
When I startet the adapter and register one twinkly and now the adapter restarts I get an error and can't control the twinkly

**Screenshots & Logfiles**  
twinkly.0 | 2022-12-01 22:38:43.887 | info | Startup complete
-- | -- | -- | --
twinkly.0 | 2022-12-01 22:38:43.886 | error | Could not get Wohnzimmer.timer Error: proxyFromEnv.getProxyForUrl is not a function
twinkly.0 | 2022-12-01 22:38:43.882 | error | Could not get Wohnzimmer.name Error: proxyFromEnv.getProxyForUrl is not a function
twinkly.0 | 2022-12-01 22:38:43.879 | error | Could not get Wohnzimmer.ledSat Error: proxyFromEnv.getProxyForUrl is not a function
twinkly.0 | 2022-12-01 22:38:43.876 | error | Could not get Wohnzimmer.ledPlaylist Error: proxyFromEnv.getProxyForUrl is not a function
twinkly.0 | 2022-12-01 22:38:43.870 | error | [updatePlaylist.Wohnzimmer] Could not get playlist Error: proxyFromEnv.getProxyForUrl is not a function
twinkly.0 | 2022-12-01 22:38:43.866 | error | Could not get Wohnzimmer.ledMovie Error: proxyFromEnv.getProxyForUrl is not a function
twinkly.0 | 2022-12-01 22:38:43.857 | error | [updateMovies.Wohnzimmer] Could not get movies Error: proxyFromEnv.getProxyForUrl is not a function
twinkly.0 | 2022-12-01 22:38:43.853 | error | Could not get Wohnzimmer.mode Error: proxyFromEnv.getProxyForUrl is not a function
twinkly.0 | 2022-12-01 22:38:43.849 | error | Could not get Wohnzimmer.ledEffect Error: proxyFromEnv.getProxyForUrl is not a function
twinkly.0 | 2022-12-01 22:38:43.846 | error | Could not get Wohnzimmer.ledColor Error: proxyFromEnv.getProxyForUrl is not a function
twinkly.0 | 2022-12-01 22:38:43.843 | error | Could not get Wohnzimmer.ledBri Error: proxyFromEnv.getProxyForUrl is not a function
twinkly.0 | 2022-12-01 22:38:43.839 | error | Could not get Wohnzimmer.firmware Error: proxyFromEnv.getProxyForUrl is not a function
twinkly.0 | 2022-12-01 22:38:43.832 | error | [Wohnzimmer.getListOfLEDEffects] Could not get effects! proxyFromEnv.getProxyForUrl is not a function
twinkly.0 | 2022-12-01 22:38:43.826 | error | [Wohnzimmer.interview.details] Error: proxyFromEnv.getProxyForUrl is not a function
twinkly.0 | 2022-12-01 22:38:43.822 | error | [Wohnzimmer.interview.fw] Error: proxyFromEnv.getProxyForUrl is not a function
twinkly.0 | 2022-12-01 22:38:43.282 | info | starting. Version 1.0.9 (non-npm: patrickbs96/ioBroker.twinkly) in /opt/iobroker/node_modules/iobroker.twinkly, node: v16.18.1, js-controller: 4.0.23
twinkly.0 | 2022-12-01 22:38:43.101 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system

**Versions:**  
 - Adapter version: 1.0.9 I also tried 1.0.7
 - JS-Controller version: 4.0.23
 - Node version: v16.18.1
 - Operating system:  Linux Buster

**Comment by patrickbs96** [comment]
Hi there, I'm not quite sure where that problem is coming from. I guess it's coming from Axios itself.
Can you install the current version from github please, I added a few lines of logging. Maybe that can help. 
You need the activate log level debug for the added lines to show up. Please send me the log afterward. Thanks.

**Comment by basti85goe** [comment]
[Wohnzimmer.request.POST] TypeError: "proxyFromEnv.getProxyForUrl is not a function", stack="TypeError: proxyFromEnv.getProxyForUrl is not a function at setProxy (/opt/iobroker/node_modules/iobroker.twinkly/node_modules/axios/dist/node/axios.cjs:2271:35) at dispatchHttpRequest (/opt/iobroker/node_modules/iobroker.twinkly/node_modules/axios/dist/node/axios.cjs:2548:7) at new Promise (<anonymous>) at http (/opt/iobroker/node_modules/iobroker.twinkly/node_modules/axios/dist/node/axios.cjs:2316:10) at Axios.dispatchRequest (/opt/iobroker/node_modules/iobroker.twinkly/node_modules/axios/dist/node/axios.cjs:3241:10) at Axios.request (/opt/iobroker/node_modules/iobroker.twinkly/node_modules/axios/dist/node/axios.cjs:3591:33) at Function.wrap [as request] (/opt/iobroker/node_modules/iobroker.twinkly/node_modules/axios/dist/node/axios.cjs:27:15) at Twinkly.request (/opt/iobroker/node_modules/iobroker.twinkly/lib/twinkly.js:1367:49) at Twinkly._sendRequestTwinklyCodeCheck (/opt/iobroker/node_modules/iobroker.twinkly/lib/twinkly.js:1293:35) at Twinkly.login (/opt/iobroker/node_modules/iobroker.twinkly/lib/twinkly.js:224:37)"
--

**Comment by patrickbs96** [comment]
Thanks for the input, I had a look into this. `proxy-from-env` is already included due to the dependency `axios`. 
But for some reason it wasn't properly installed for you. What you can try is 

1. cd /opt/iobroker/node_modules/iobroker.twinkly
2. rm -r node_modules
3. npm install

Then it should add the missing dependency.

**Comment by patrickbs96** [comment]
There seem to be some problems with the version of axios. I upgraded to the latest version, maybe that will help. Otherwise I'll downgrade.
Try installing the branch: https://github.com/patrickbs96/ioBroker.twinkly/tree/develop

**Comment by basti85goe** [comment]
no it also doesn't work.... the only way I get it work is with my dependency fix...
so maybe just add to dependency...

**Comment by patrickbs96** [comment]
Alright, so for testing purposes I created two branches. One with a downgrade of axios and one with the added dependency. Please test these out and let me know if one or both of them work.

Downgrade: https://github.com/patrickbs96/ioBroker.twinkly/tree/proxy_error-axios_downgrade
Add dependency: https://github.com/patrickbs96/ioBroker.twinkly/tree/proxy_error-axios_add_dependency

**Comment by basti85goe** [comment]
no sorry... I don't get it work... just with my trick to manually download "proxy-from-env" from git

**Comment by patrickbs96** [comment]
> 1. cd /opt/iobroker/node_modules/iobroker.twinkly
> 2. rm -r node_modules
> 3. npm install
> 
> Then it should add the missing dependency.

Did you try doing this? When I do this it adds `proxy-from-env` to the `.\iobroker.twinkly\node_modules` directory.
