### ISSUE TITLE
Error: Mandatory property type missing

### ISSUE THREAD

**Issue by eric2905** [patrickbs96/ioBroker.twinkly#209]
Getting a lot of error messages in log:

twinkly.0 | 2022-12-21 19:25:19.139 | error | [updateMovies.Weihnachtsbaum] Cannot update movies! mandatory property type missing!
-- | -- | -- | --
twinkly.0 | 2022-12-21 19:25:19.138 | error | setObject Weihnachtsbaum.ledMovie mandatory property type missing

js-controller 4.0.24
Admin 6.3.4
Twinkly 1.0.11

If any more information is needed, just ask

**Comment by patrickbs96** [comment]
Delete the state `Weihnachtsbaum.ledMovie` and restart the adapter. It should create it properly then.

**Comment by eric2905** [comment]
Tried it before opening an Github Issue.

Did it now two times (second was deleting the entire objects tree and not only the one data point) and now it works.

Thx and happy holidays,
Eric (eric2905)

**Comment by patrickbs96** [comment]
Thanks, you too 🎄
