### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [patrickbs96/ioBroker.twinkly#34]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/patrickbs96/ioBroker.twinkly

- [ ] [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 patrickbs96 <patrickbsimon96@gmail.com>" at the start of LICENSE

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by patrickbs96** [comment]
@Apollon77 ist da ein Fehler im ioBrokerChecker? Ich habe das aktuelle Jahr bereits drin.

**Comment by Apollon77** [comment]
wirklich? https://github.com/patrickbs96/ioBroker.twinkly/blob/master/LICENSE ? ;-))

**Comment by patrickbs96** [comment]
Verdammt an die Licence habe ich gar nicht mehr gedacht... Danke dir :-)

**Comment by ioBrokerChecker** [comment]
Thanks, that all bugs have been fixed.

**Comment by ioBrokerChecker** [comment]
Thanks, that all bugs have been fixed.
