### ISSUE TITLE
admin 5 tab.html not found

### ISSUE THREAD

**Issue by mcuiobroker** [patrickbs96/ioBroker.twinkly#72]
![image](https://user-images.githubusercontent.com/84818934/131709294-f8eca251-1b7d-496f-9345-1a542553e4d2.png)

**Versions:**  
 - Adapter version: 0.1.8
 - JS-Controller version: 3.3.15
 - Node version: 12.22.6
 - Operating system: linux

**Comment by patrickbs96** [comment]
@mcuiobroker Kannst du bitte einmal die neueste Version einspielen und prüfen ob es immer noch auftaucht? 
Ich hatte den Fehler während des Codereviews im Februar eigentlich behoben gehabt.

**Comment by mcuiobroker** [comment]
Leider auch mit der neuen Version 0.1.9 keine Änderung:
![image](https://user-images.githubusercontent.com/84818934/132104150-b63579fd-6b71-48fc-b3d1-a555fac115cb.png)

**Comment by patrickbs96** [comment]
Die existiert nicht, da ich die Ansicht garnicht freigeschaltet habe... ioBroker denkt wohl trotzdem das diese aktiviert ist. 

Könntest du bitte einmal prüfen ob in der `system.adapters.twinkly.0` ein Eintrag mit adminTab enthalten ist?
Ich habe das Gefühl, dass die Informationen in diesem Bereich nicht durch ein Update aktualisiert werden.
Also entweder diesen Bereich manuell löschen oder die Instanz neuerzeugen, dann sollte es hoffentlich weg sein.

**Comment by mcuiobroker** [comment]
Inhalt:
![image](https://user-images.githubusercontent.com/84818934/132107349-b5d48f54-dfa7-413b-9d04-1ef2e7229c71.png)

**Comment by patrickbs96** [comment]
Ah sorry, ich hätte erwähnen sollen, dass die Information in dem "Objekt bearbeiten" Dialog zu finden ist:
![image](https://user-images.githubusercontent.com/49351462/132109440-6ca2a040-167b-4425-b6a9-7c5868dc2519.png)

**Comment by mcuiobroker** [comment]
```
"adminTab": {
      "singleton": true,
      "name": {
        "en": "Twinkly",
        "de": "Twinkly",
        "ru": "Твинкли",
        "pt": "Twinkly",
        "nl": "Twinkly",
        "fr": "Twinkly",
        "it": "Twinkly",
        "es": "Twinkly",
        "pl": "Twinkly",
        "zh-cn": "Twinkly"
      },
```

**Comment by mcuiobroker** [comment]
Gelöscht und weg:
![image](https://user-images.githubusercontent.com/84818934/132109647-7a7ab645-00a7-427c-a3c2-733591ef7b4f.png)
Danke.

**Comment by patrickbs96** [comment]
@mcuiobroker Kannst du bitte auf die Version 0.1.12 updaten? 
Ich hatte in 0.1.10 das Sentry Logging für fehlende API Werte ergänzt, damit ich automatisch benachrichtigt werde falls die Twinkly Lichterketten neue Informationen übertragen. Fälschlicherweise hatte ich aber nicht geprüft ob dieser Eintrag bereits an mich gesendet wurden und dadurch wird bei jedem poll ein neuer Eintrag erzeugt...

**Comment by mcuiobroker** [comment]
Ist aber noch nicht im repropsitory von beta /ioBroker

**Comment by patrickbs96** [comment]
ioBroker braucht manchmal länger bis die neue Version im latest auftaucht, ansonsten über den neuen Tab npm installieren. Darüber wird sie im Endeffekt eh installiert.
Der Adapter wurde aber vorhin ins Stable aufgenommen, sollte also von nun an auch darüber klappen :-)
