### ISSUE TITLE
Make color_config writable

### ISSUE THREAD

**Issue by patrickbs96** [patrickbs96/ioBroker.twinkly#91]
Try to make `color_config` writable to change settings.

New Mode available: **color**

**Comment by RkcCorian** [comment]
In case I can wish something... Color control als HEX would be nice :-) But I can also handle HUE but prefer HEX 🙈

**Comment by patrickbs96** [comment]
I've also added the option to write it as HEX :-)
You can try out the new feature with version 0.2.2
let me know if it works

**Comment by RkcCorian** [comment]
It is working!!! :-) Many thanks!!!!! You saved XMas :-)

**Comment by patrickbs96** [comment]
Great, glad I could help 😊

**Comment by patrickbs96** [comment]
Just received a message from Sentry that there is also white available in the colorConfig.
I'll see how I can implement that later

**Comment by patrickbs96** [comment]
white is now also available in version 0.2.3

**Comment by RkcCorian** [comment]
Many thanks! What shall be the changed behaviour now? That also white is selectable? Greetings!

**Comment by patrickbs96** [comment]
Yes correct, the new Datapoint will be created if the light is RGBW
